ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQCrr9 FOREIGN KEY (FCreatorID) REFERENCES T_PM_User (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQLUfg FOREIGN KEY (FLastUpdateUserID) REFERENCES T_PM_User (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQCU3n FOREIGN KEY (FControlUnitID) REFERENCES T_ORG_OUPartCtrl (FUnitID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQUsrf FOREIGN KEY (CFCustomerNameID) REFERENCES T_ISCM_CRMCustomerfile (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQEhlk FOREIGN KEY (CFVehNumberID) REFERENCES T_ISCM_VMSVehManageMent (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQRvp0 FOREIGN KEY (CFDriverNameID) REFERENCES T_ISCM_VMSDriverManager (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQSppm FOREIGN KEY (CFExceptionTypeID) REFERENCES T_ISCM_BDMDataDictionary (FID);

ALTER TABLE CT_TMS_TransportServiceQuelity ADD CONSTRAINT CFK_TMS_TMSTSQPrv7 FOREIGN KEY (CFOperateUnitID) REFERENCES T_ORG_Admin (FID);

